apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b55jte2as-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b55jte2as-python 
  name: b55jte2as-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b55jte2as-python 
